services:
  mysql:
    image: mysql:8.4
    container_name: payment-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  rabbitmq:
    image: rabbitmq:4-management
    container_name: payment-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: payment-service

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      DB_HOST: mysql
      DB_PORT: 3306

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      - mysql
      - rabbitmq

volumes:
  mysql_data:
  rabbitmq_data:
